# ENFILADE · ARCADE — born-in colors (kitty reads this at spawn, never again)
background            #120a10
foreground            #f2dde6
cursor                #ff4f7b
cursor_text_color     #120a10
selection_background  #ff4f7b
selection_foreground  #120a10
url_color             #4fd6ff
active_border_color   #ff4f7b
inactive_border_color #1d1019
active_tab_background   #ff4f7b
active_tab_foreground   #120a10
inactive_tab_background #1a0e17
inactive_tab_foreground #8d6f80
color0  #1d1019
color8  #4a2a3c
color1  #ff4f7b
color9  #ff7396
color2  #5ce0a5
color10 #7eeab9
color3  #ffc24f
color11 #ffd178
color4  #4fa9ff
color12 #74bdff
color5  #c45fff
color13 #d484ff
color6  #4fd6ff
color14 #78e1ff
color7  #f2dde6
color15 #fbeef3
